version: "3"
services:
  springboot-app:
    container_name: wishlist-app
    image: wishlist-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: wishlist_db
      MYSQL_ROOT_PASSWORD: root
